### YamlMime:PythonClass
uid: azure.containerregistry.DigestValidationError
name: DigestValidationError
fullName: azure.containerregistry.DigestValidationError
module: azure.containerregistry
inheritances:
- builtins.ValueError
summary: 'Thrown when a manifest digest validation fails.

  :param str message: Message for caller describing the reason for the failure.'
constructor:
  syntax: DigestValidationError(message)
  parameters:
  - name: message
methods:
- uid: azure.containerregistry.DigestValidationError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.containerregistry.DigestValidationError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.containerregistry.DigestValidationError.args
  name: args
