### YamlMime:PythonClass
uid: azure.ai.ml.identity.CredentialUnavailableError
name: CredentialUnavailableError
fullName: azure.ai.ml.identity.CredentialUnavailableError
module: azure.ai.ml.identity
inheritances:
- azure.core.exceptions.ClientAuthenticationError
summary: The credential did not attempt to authenticate because required data or state
  is unavailable.
constructor:
  syntax: 'CredentialUnavailableError(message: object | None = None, response: _HttpResponseCommonAPI
    | None = None, **kwargs: Any)'
  parameters:
  - name: message
    defaultValue: None
  - name: response
    defaultValue: None
